trigger:
- master

pool:
  name: MyAgentPool
  demands: Agent.Name -equals Agent-1

steps:
- task: AgentJob@1
  displayName: 'Agent Job'
  inputs:
    agentPool: 'MyAgentPool'
    agentSpecification: 'Agent-1'
    continueOnError: false
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11.0.18'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
