trigger:
- master

pool: 
  name: Default

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
      sudo echo "heelo World" > /opt/hello.txt
  